### ISSUE TITLE
Remove waffle.io

### ISSUE THREAD

**Issue by smem22** [open-learning-exchange/open-learning-exchange.github.io#2346] opened 2019-06-04 14:40 UTC
###

### Screenshots

![Screen Shot 2019-06-04 at 10 32 48 AM](https://user-images.githubusercontent.com/45078726/58887767-34d32980-86b4-11e9-80e1-9670fc4e7931.png)

### Proposed solution
To remove that section, the simpler solution would be to get to the page source code and remove that section from there.

**Comment by Liew211** [comment] 2019-06-04 14:50
@smem22 this is a duplicate of an issue that has already been opened at #2342.

**Closed** 2019-06-04 14:51 UTC
