### ISSUE TITLE
Syntax error <!doctype html> while clicking on Virtual intern

### ISSUE THREAD

**Issue by shahswet** [open-learning-exchange/open-learning-exchange.github.io#695] opened 2017-04-18 22:19 UTC
![htmlerror](https://cloud.githubusercontent.com/assets/17865137/25155314/a7c7b496-2451-11e7-973a-755a72751054.jpg)

Whenever we click on Virtual Intern, syntax error **<!doctype html>** blinks for 2 second and goes away.

**Comment by mappuji** [comment] 2017-04-18 22:23
I don't know the core of engine of MDWiki who make it possible a markdown file view as it is an HTML, but I think the issue you've mentioned @shahswet is a matter of rendering time.

Anyone who have more experience with MDWiki are welcome to give a suggestion.

**Comment by waryhermit** [comment] 2017-04-18 22:47
@shahswet I don't get that when I click it. What browser are you using I wonder?

**Comment by shahswet** [comment] 2017-04-18 22:57
@waryhermit google chrome

**Comment by kylemathias** [comment] 2017-04-18 23:08
I saw it for a split second, but after that it never appeared again. on Chrome

**Comment by dogi** [comment] 2017-04-19 00:36
hmm my chrome on ubuntu is not having that issue ... maybe my inet and/or computer is too fast

**Comment by Loshma93** [comment] 2017-04-19 20:09
@shahswet I don't have the problem which you are talking about. When I click on Virtual Interns "index.md" page is viewing.
![image](https://cloud.githubusercontent.com/assets/24893117/25199941/660715fa-2501-11e7-9f0a-08f591b80ab5.png)

**Comment by waryhermit** [comment] 2017-04-19 23:30
I couldn't reproduce with the following browsers:

Firefox 52.0.1
Chrome 57.0.2987.133
IE 11
Edge 40.15063

@shahswet What version of chrome are you using?

**Comment by shahswet** [comment] 2017-04-19 23:34
@waryhermit I am using chrome Version 57.0.2987.133 (64-bit)

**Comment by waryhermit** [comment] 2017-04-19 23:38
@shahswet hmm, I feel like this might be a problem with the MDwiki itself.

If you go to http://dynalon.github.io/mdwiki/#!index.md and click "MDwiki" do you get a similar problem?

**Comment by shahswet** [comment] 2017-04-19 23:41
@waryhermit Nope, I am not getting similar problem when i click "MDwiki". It's working fine.

**Comment by waryhermit** [comment] 2017-04-20 18:03
@shahswet Well if you have any thoughts on how to reproduce or fix this issue I am certainly interested to hear them, but as it is I think this issue is going to sit unfixed for a very long time.

**Comment by mappuji** [comment] 2017-05-01 07:04
@waryhermit and @shahswet [here](http://dynalon.github.io/mdwiki/#!index.md) MDWiki needs time to load. I think, the problem mentioned is a matter of rendering time, but it is awesome if we can increase the rendering time.

**Comment by kylemathias** [comment] 2017-05-24 23:49
This is an extremely small problem that appears to require way more time than it is worth. Im closing this for now.

**Closed by kylemathias** 2017-05-24 23:49 UTC
Labels: very difficult
