### ISSUE TITLE
FAQ for github issues 

### ISSUE THREAD

**Issue by fsjoyti** [open-learning-exchange/open-learning-exchange.github.io#59] opened 2016-05-26 19:40 UTC
We could do a separate tab for answering frequently asked questions such as merge conflicts or not being able to do a pull from the github remote repository. It could be part of the faq tab in markdown wiki or a separate tab altogether

**Comment by dogi** [comment] 2016-05-26 20:47
duplicate of https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/37

**Closed by dogi** 2016-05-26 20:47 UTC
