### ISSUE TITLE
Clicking links on the wiki doesn't take me to the top of new page

### ISSUE THREAD

**Issue by yeshks** [open-learning-exchange/open-learning-exchange.github.io#1770] opened 2018-05-06 02:06 UTC
Whenever I click any link on the wiki, I expect to end up on the top of the page that I'm opening but I end up in the middle and have to scroll all the way up of every page making for a bad user experience.

Recreate the issue by visiting the [wiki](http://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) and scrolling to the **_Step 5 - Keeping Fork Updated_** section and then click on the link in that section. You get to the page at the following area instead of the top.

<img width="1334" alt="screen shot 2018-05-05 at 10 01 41 pm" src="https://user-images.githubusercontent.com/30668693/39669097-0493bd2e-50b0-11e8-842e-b1a20e22e220.png">

The issue is persistent with all the links somehow.

**Comment by sahilph** [comment] 2018-05-06 04:00
I tested the link you mentioned and a couple of other links too. It always got me to the top.
What did you do exactly?

Also please use the specified issue format when creating a issue.

**Comment by yeshks** [comment] 2018-05-06 04:09
Can you try using firefox? The problem doesn't appear in chrome.
Also can you ellaborate on the specified format? I tried to follow this [link](http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md)

**Comment by sahilph** [comment] 2018-05-06 04:25
whenever you click `New Issue` you get a template. You should use that when creating a issue. It makes it easier for review.

Also yes you are right. It does not scroll to top in Firefox. Seems to be issue with MDWiki.

**Comment by xyb994** [comment] 2018-05-24 19:43
The issue is likely caused by https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1817#issuecomment-391107574, closing it for now.

**Closed by xyb994** 2018-05-24 19:43 UTC
