### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#1329] opened 2017-10-19 14:06 UTC
In http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations.md there is a broken link `FAQ`
is pointing to http://open-learning-exchange.github.io/#!./pages/vi/interns/vi-faq.md#Technical_Issues_and_Questions and should point to http://open-learning-exchange.github.io/#!./pages/vi/vi-faq.md#Technical_Issues_and_Questions

**Comment by aas919** [comment] 2017-10-19 21:29
@dogi The issue is already opened here https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1322 and I have opened a pull request to fix it https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1323. Please review the same.

**Comment by xyb994** [comment] 2017-10-20 17:30
Closing this as PR https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1323 was merged.

**Closed by xyb994** 2017-10-20 17:30 UTC
Labels: bug, easy, help wanted, ready
