### ISSUE TITLE
First Steps Page Link to MDWiki

### ISSUE THREAD

**Issue by akshayuncc** [open-learning-exchange/open-learning-exchange.github.io#1804] opened 2018-05-16 15:01 UTC
### Problem
On the First Steps page you will find "All content and images © by Open Learning Exchange Website generated with MDwiki © Timo Dörr and contributors" at the bottom of the page. If you click on the MDWiki link you will be directed to the MDWiki - Markdown page. If you click back you will not be able to go back to the First Steps web page. 

### Screenshots

![image](https://user-images.githubusercontent.com/25532941/40375488-bf874ee6-5db9-11e8-904c-44ae7b5c5859.png)

![image](https://user-images.githubusercontent.com/25532941/40375506-cb14920a-5db9-11e8-9cb8-e12e3255c9c7.png)

### Proposed solution

N/A
(Working on it)

**Comment by xyb994** [comment] 2018-05-17 00:13
@akshayuncc 

Bell is on feature freeze, as you can see at https://github.com/open-learning-exchange/BeLL-Apps/commits/dev. We are focus on developing [planet](https://github.com/open-learning-exchange/planet) at this time.

The main purpose is to get you familiar with the whole workflow and make sure you know how to use git and GitHub. Please try to raise issues about our MDwiki so you can actually get things move on faster and finish first steps.

**Comment by akshayuncc** [comment] 2018-05-22 16:16
@xyb994 ok, thank you. Instead of creating a new issue I just update the issue.

**Comment by xyb994** [comment] 2018-05-22 19:04
Related to https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1816

**Comment by xyb994** [comment] 2018-05-24 19:38
Closing this as this is essentially caused by the same issue as in #1816

**Closed by xyb994** 2018-05-24 19:38 UTC
