### ISSUE TITLE
Remove waffle.io section #2347

### ISSUE THREAD

**Issue by smem22** [open-learning-exchange/open-learning-exchange.github.io#2347] opened 2019-06-04 15:31 UTC
### Remove waffle.io from section [intern orientation]
[intern orientation]: http://open-learning-exchange.github.io/#!./pages/robots/rbts-intern-orientation.md

### Steps to reproduce the problem
Go to http://open-learning-exchange.github.io/#!./pages/robots/rbts-intern-orientation.md

### Screenshots of the Issue

![Screen Shot 2019-06-04 at 10 32 48 AM](https://user-images.githubusercontent.com/45078726/58891667-f42ade80-86ba-11e9-8aa4-ec61fca4c4a0.png)

### Proposed solution
I went to the page source code and removed the section where the waffle.io paragraph was.

![Screen Shot 2019-06-04 at 11 14 16 AM](https://user-images.githubusercontent.com/45078726/58891942-64d1fb00-86bb-11e9-83be-92de38474b8d.png)

### Screenshots of the proposed solution
![Screen Shot 2019-06-04 at 11 16 31 AM](https://user-images.githubusercontent.com/45078726/58892040-8c28c800-86bb-11e9-80de-e01c5f1de1a4.png)

**Comment by samuelchen1213** [comment] 2019-06-04 18:21
@smem22 this is a duplicate of an issue that has already been opened at #2342. I believe you are trying to solve the issue. Please look through the first steps again and read the instructions. You need to make a new branch for this issue, go into pages, robots, and edit the rbts-intern-orientation.md file. Then submit a **pull request**

**Closed** 2019-06-04 18:23 UTC
