### ISSUE TITLE
"Why Install Vagrant link" is Not Available

### ISSUE THREAD

**Issue by ofrank23447** [open-learning-exchange/open-learning-exchange.github.io#1465] opened 2018-01-12 23:27 UTC
When clicked "Why Install Vagrant" under Vagrant step, it leads to a page that says "Page Not Found".  
![image](https://user-images.githubusercontent.com/24216313/34899313-f5a7cf0a-f7ac-11e7-87d6-2606f215282e.png)

![image](https://user-images.githubusercontent.com/24216313/34899305-e3eef130-f7ac-11e7-9620-b6c45a781f0c.png)

So, I suggest taking the link down and attach https://24ways.org/2014/what-is-vagrant-and-why-should-i-care/ as the link as it discusses clearly what/how/why Vagrant is used.

**Comment by xyb994** [comment] 2018-01-13 01:41
This is a duplicate of #1455 and PR #1460 is already created.

**Closed by xyb994** 2018-01-13 01:41 UTC
