### ISSUE TITLE
"Markdown Tutorial" Link is Dead (404 Error Page)

### ISSUE THREAD

**Issue by vishwakarmaanil** [open-learning-exchange/open-learning-exchange.github.io#1532] opened 2018-01-18 09:16 UTC
Here is the link to the page "http://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-markdown.md"

![](https://image.ibb.co/b6vgxR/6.png)

**"Markdown Tutorial"** link is not functional.

**Comment by kylemathias** [comment] 2018-01-18 20:11
go ahead and make the fix.

**Comment by vishwakarmaanil** [comment] 2018-01-18 20:51
@kylemathias Please check this Pull request https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1535

**Comment by Jackbui96** [comment] 2018-01-19 01:50
@vishwakarmaanil Hello, actually I am working on that issue right now.

**Comment by Ivaylo2017** [comment] 2018-01-20 17:46
@vishwakarmaanil Hi bud. Why not link to [https://www.markdowntutorial.com](https://www.markdowntutorial.com/) instead?
[http://mdp.tylingsoft.com](http://mdp.tylingsoft.com ) seems to be the site of "Markdown Plus" editor

**Comment by xyb994** [comment] 2018-01-20 20:24
@Ivaylo2017 Thanks for catching the problem.

http://tylingsoft.github.io/tutorial.md/#whats-markdown looks more like the "original" one. See archive here: https://web.archive.org/web/20170425051003/http://tylingsoft.com/tutorial.md/

@Jackbui96 @vishwakarmaanil Our bad didn't notice you both raised the same issue and it end up like this. @Jackbui96 [raise the issue first](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1457) but @vishwakarmaanil opened the PR  first. Since non of you found the "close to original" url, to make it fair, I will be closing both of your PRs and fixing the url [here](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1547/files#diff-5b72c36d6c2ea1941fbdaa2e0edc04a7R132) when restructuring the file. Both of you will loose one of the PR count in Step 8 so please try to raise another issue.

Related PRs:
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1540
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1535
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1556

**Comment by xyb994** [comment] 2018-01-20 20:27
Closing this, duplicate of #1457

**Closed by xyb994** 2018-01-20 20:27 UTC
