### ISSUE TITLE
First Steps page Contributors drop downlist unusual behaviour

### ISSUE THREAD

**Issue by akshayuncc** [open-learning-exchange/open-learning-exchange.github.io#1817] opened 2018-05-22 16:50 UTC
### Problem
On the First Steps if you click any item after Take home under Contributors list you will be directed to the next page. But if you scroll down on the first steps page and then select a link from the Contributors page you will be taken to the bottom page of the selected item from the drop down list.

### Steps to reproduce the problem

Scroll down to the end of the first steps page and then select an item after Take Home from the Contributors list. You will be directed to the end of the next page.

### Screenshots

![image](https://user-images.githubusercontent.com/25532941/40377213-5a1c7342-5dbe-11e8-88c3-637f291c9c26.png)

![image](https://user-images.githubusercontent.com/25532941/40377255-72197b3e-5dbe-11e8-8981-101cb8078d86.png)

![image](https://user-images.githubusercontent.com/25532941/40377278-80bd5070-5dbe-11e8-93a5-d69d2075b86c.png)

### Proposed solution

N/A

**Comment by akshayuncc** [comment] 2018-05-22 16:51
Working on it.

**Comment by xyb994** [comment] 2018-05-22 19:11
How do you plan to resolve this?
This is only happening on Firefox, I'm guessing it has something to do with the url containing `#!`and Firefox does not know it's a new page.

**Comment by akshayuncc** [comment] 2018-05-22 19:18
Yes @xyb994 it seems to be only happening in Firefox . And as Firefox is the recommended browser hence I raised this issue. And exactly firefox does not seem to know it's a new page. 
Still working on it hope to figure out a solution.

**Comment by xyb994** [comment] 2018-05-22 19:39
Yeah, Firefox is the recommended browser for BeLL.

**Comment by xyb994** [comment] 2018-05-24 19:43
Duplicate of #1562

**Closed by xyb994** 2018-05-24 19:43 UTC
