### ISSUE TITLE
A question about step 2: Vagrant Windows

### ISSUE THREAD

**Issue by fangninghe** [open-learning-exchange/open-learning-exchange.github.io#429] opened 2017-01-10 23:19 UTC
When I came into this step, I was stuck for a little while. For this sentence "_In our case, the directory is ole--vagrant-vi. So, if you open up a **Command Prompt** on your machine and you type `cd ole--vagrant-vi` followed by `vagrant global-status`, you will see a screen similar to this_" I thought a little bit about whether using regular **_Command Prompt_** or **_Command Prompt(Admin)_**. The result turned out **_Command Prompt(Admin)_** is not working for those commands.

I thought you guys have already made it clear, but since I had that thought passing through my mind even only for just a second, I would like to provide it as a suggestion.

So how about add a sentence like this:
"_Just a gentle reminder, only regular **Command Prompt** is used, not the **Command Prompt(Admin)** which is for System Administrator to use_"

**Comment by waryhermit** [comment] 2017-01-10 23:32
@fangninghe It works fine for me / win10 admin command prompt. What error did you get?

**Comment by dogi** [comment] 2017-01-11 02:12
# log of the chat about this issue on gitter

Alex @fangninghe 18:37
[![blob](https://files.gitter.im/open-learning-exchange/chat/47p9/thumb/blob.png)](https://files.gitter.im/open-learning-exchange/chat/47p9/blob)

@waryhermit
did I type right?

waryhermit @waryhermit 18:38
your not in the right folder yet, cd = change directory
so it can't find the folder you told it to go to
you need to get to the C:\Users\YOUR_USERNAME\ole--vagrant-vi

Alex @fangninghe 18:44
@dogi yeah, that also what I mean, there are two Command Prompt in my system
@waryhermit
one is Command Prompt and the other is Command Prompt(Admin)

waryhermit @waryhermit 18:46
I understand, either will work. The command did not work not because it was admin, but because what you asked of it was invalid.

Alex @fangninghe 18:48
[![blob](https://files.gitter.im/open-learning-exchange/chat/sup0/thumb/blob.png)](https://files.gitter.im/open-learning-exchange/chat/sup0/blob)

waryhermit @waryhermit 18:48
Why it doesn't work is because the path the two prompts defaults to. You can change the path quite easily with the cd command, so you might add a note about that rather

Alex @fangninghe 18:50
Ok, got it

waryhermit @waryhermit 18:50
for example cd %homepath% would take you to the same folder that the non-admin prompt starts at
so you could either tell everyone to type cd %HOMEPATH% so it will work no matter were they have their prompt pointed at the moment or you could just make a note explaining that they have to be in the right directory.

Alex @fangninghe 18:53
@waryhermit , so is there any necessary for me to make a PR to fix it, or just keep it? Just double check

waryhermit @waryhermit 18:55
If you still feel like its an issue that should be fixed, you can make a PR or update your issue explain how you would make it more clear. If you have changed your mind and don't think it needs to be changed, you can explain why and close your issue. Up to you.

**Comment by dogi** [comment] 2017-01-11 02:28
think part of the problem is that should introduce `git bash` here
so that every windows user opens same thing for doing the vagrant stuff

@fangninghe do you know `git bash`? It got install with git or in other word it is now already on your system

@waryhermit do you agree that we have too many option here? ;)

Let me speak about the ones I know where to start vagrant stuff:
X | Normal | Admin
---|---|---
Command Prompt (cmd.exe) | X | X
PowerShell (?.exe) | X | X
Git bash | X | X


@fangninghe and @waryhermit I have also to say that I am a little bit biased here ...
@dogi <3  https://github.com/git-for-windows/git

**Comment by fangninghe** [comment] 2017-01-11 18:44
@dogi , maybe we can add all the reference to make the content more comprehensive, what do you think?

**Comment by dogi** [comment] 2017-01-12 01:53
@fangninghe I think since vagrant for windows page is kinda new (thanks @aberdean ;) )
there are lots of things to improve there ...

I would mostly add `git bash` there and how to use `vagrant` on top of that

Does that make sense?
@fangninghe do you wanna try a PR here?

**Comment by fangninghe** [comment] 2017-01-12 21:08
@dogi , how about like this:
## Windows
First of all, Vagrant only works if you are in the correct directory, which is a directory that includes a file called Vagrantfile. In our case, the directory is ole--vagrant-vi.  Here, three options are provided for you to operate Vagrant.

**1. Command Prompt**
Sometimes there are two kinds of Command Prompt listed in your system. One is **Command Prompt**, and the other is **Command Prompt(Admin)**. As is shown below:

![admin command](https://cloud.githubusercontent.com/assets/22717583/21906882/2b8af74c-d8db-11e6-90f4-fd8764bce05a.png)

Basically, they are the same. the only difference is the default path. For **Command Prompt(Admin)**, the default path is `C:Windows\system32` and **Command Prompt** is `C:\Users\YOUR_USERNAME`.  You can use either **Command Prompt** or **Command Prompt(Admin)** to access the right directory for Vagrant.

**2. Windows PowerShell**
Windows PowerShell is a default shell interface installed in your machine. When you open it, the default path is `C:\Users\YOUR_USERNAME`.

**3. Git Bash**
Actually, **Git Bash** is also a good choice. You can download it from [here](https://git-scm.com/download/win). As you open **Git Bash**, you will find the default path of it is also `C:\Users\YOUR_USERNAME`.

As is mentioned above, the correct directory of Vagrant is `C:\Users\YOUR_USERNAME\ole--vagrant-vi`
So as long as you are at the correct directory, you can use any of those three options to run commands related to Vagrant. 

Now, just choose one option illustrated above and learn some basic commands of Vagrant.
If you type `cd ole--vagrant-vi` followed by `vagrant global-status`, you will see a screen similar to this.......

**_The rest is the same as before_**

**Comment by dogi** [comment] 2017-01-12 23:41
@fangninghe awesome - very good

point 3 needs some change
`git bash` got already installed with the ole--vagrant-vi script
this is part of `git` is necessary for our installation

also
I would also change "Now, just choose one option illustrated above" into something like that alll following command work in all the options illustrated above, but we suggest mostly using `git bash` ...

**Comment by dogi** [comment] 2017-01-13 00:04
@fangninghe perfect - I think this is ready for a PR ;)

**Closed** 2017-01-13 18:56 UTC
