### ISSUE TITLE
Side Menu is disturbing main content

### ISSUE THREAD

**Issue by Loshma93** [open-learning-exchange/open-learning-exchange.github.io#622] opened 2017-04-04 23:11 UTC
In internorientation.md page the side Menu is disturbing Main Content in the page. You can see an example here:
![image](https://cloud.githubusercontent.com/assets/24893117/24682921/1577d1c6-1951-11e7-8c93-0ea82fa61f3e.png)

I think it would be better to compress or move side menu to left if possible. So that it won't disturb main content.

**Comment by waryhermit** [comment] 2017-04-05 12:02
We are aware of this problem - but its a problem with the markdown wiki code not any of the markdown files we made. It will probably take a while to figure out and fix.

**Comment by tianhaopx** [comment] 2017-04-05 20:23
In file `index.html`, at line 246, `var c=function(){var b=a("#md-left-column").css("width");a("#md-page-menu").css("width",b)};a(window).scroll(function(){c(a("#md-page-menu"));` I think that's why the width is changed when the page is scrolled.

**Comment by waryhermit** [comment] 2017-04-05 22:17
@tianhaopx OK, what effect to you think that line was intended to have?

**Comment by tianhaopx** [comment] 2017-04-06 01:21
@waryhermit `md-left-column` is the parent of `md-page-menu`. The width of `md-left-column` is defined as 25%, so that line intended to get the width of `md-left-column` and set it to `md-page-menu` when page is scrolled. It looks right, I don't know why it doesn't work.

**Comment by dogi** [comment] 2017-04-06 18:28
@Loshma93 @waryhermit @tianhaopx maybe we could just shrink the title instead of fixing the mdwiki code to support big titles ...

**Comment by waryhermit** [comment] 2017-04-06 18:41
@dogi I think this only started when we upgraded the MDwiki - so it may be fixable

**Comment by kylemathias** [comment] 2017-04-06 22:45
I noticed that when you make your browser small the side menu would disappear. Might want to fix this issue that the side menu disappear sooner when the window is resized.

**Comment by tianhaopx** [comment] 2017-04-07 00:26
@kylemathias Can you show us the screenshot that the side menu **disappears**? 
Actually, this page uses bootstrap for responsive design. When the window is small, the side menu will be moved to top.

**Comment by kylemathias** [comment] 2017-04-10 16:36
![image](https://cloud.githubusercontent.com/assets/26488295/24872146/2d5682b8-1dd1-11e7-9de3-ad28902f521c.png)
it moves the menu to the top when the screen becomes smaller.

**Comment by paulbert** [comment] 2017-04-11 16:02
Hi @Loshma93 @waryhermit @tianhaopx @dogi @kylemathias .  So the issue originates from the fact that once you give an element the property `position: fixed` it won't inherit its width from its parent element anymore.  The creator of mdwiki decided to fix this by setting the menu's width with jQuery on every scroll event.  Unfortunately, when we updated jQuery we found that the newer version gives a different result from the `.css('width')` property.

Ultimately, I don't think we need this script.  See how bootstrap itself affixes a menu at http://getbootstrap.com/css/.  They simply set the width in the css which I think is more readable and means we don't have to bother with jQuery's width properties which have been inconsistent across versions.

We'd need three sizes `width:262.5px` for screens >1200px, `width:212.5` for screens >992px and `width:100%` for smaller sizes since it doesn't add the fixed position at those sizes.

Thoughts?

**Comment by kylemathias** [comment] 2017-04-11 16:12
@paulbert sounds good to me.

**Comment by duongdo27** [comment] 2017-04-17 18:08
@waryhermit My suggested fix for the issue is change **.css("width")** to **.width()**.
According to jQuery documentation 

> The .width() method is recommended when an element's width needs to be used in a mathematical calculation.

Please checkout the fix on [my version of OLE](https://duongdo27.github.io/open-learning-duongdo.github.io/#!pages/firststeps.md)

**Comment by praneetharra** [comment] 2017-04-17 22:13
@duongdo27 @waryhermit Another issue is that when the page loads everything looks fine, but when we scroll a little the **_"left column"_** resizes and spans a little to the right.

**Comment by paulbert** [comment] 2017-04-20 22:44
@duongdo27 Just merged the CSS solution from another PR.  Good thought to switch to .width(), but your solution would need a little tweaking to make sure you adjust for the element's padding which is included in the .width() property.  The menu still grows on the first page scroll (just not enough to cover the text).

Either way I don't think we need to be running that code on every page scroll when it can just be set in the CSS.

**Closed by paulbert** 2017-04-20 22:44 UTC
Labels: bug, very difficult
